import seaborn as sns
import matplotlib.pyplot as plt
df = sns.load_dataset('planets')
df.dropna()
print("HEAD - 5")
print(df.head(5))
print()
print('DATASET INFO')
print(df.info())
print()
print('DATASET DESCRIPTION')
print(df.describe())
print()
print('DATASET UNIQUE VALUES')
print(df.nunique())
print()
#step 3
sns.histplot(data=df, x='orbital_period')
plt.title('Histogram of Orbital Period')
plt.xlabel('Orbital Period')
plt.ylabel('Frequency')
plt.show()
#step 4
sns.kdeplot(data=df, x='distance', fill=True)
plt.title('KDE Plot of Distance')
plt.xlabel('Distance')
plt.ylabel('Density')
plt.show()
sns.histplot(data=df, x='distance', kde=True)
plt.title('Histogram of Distance with KDE')
plt.xlabel('Distance')
plt.ylabel('Frequency')
plt.show()
#step 5
sns.scatterplot(data=df, x='orbital_period', y='distance', hue='method')
plt.title('Scatterplot of Orbital Period vs Distance by Method')
plt.xlabel('Orbital Period')
plt.ylabel('Distance')
plt.show()
#step 6
print('DATASET CORRELATION TABLE')
print(df.corr(numeric_only=True))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title('Heatmap of Correlation Matrix')
plt.show()